### ISSUE TITLE
When using rmlmapper as an in-process library, Jena fails to initialize

### ISSUE THREAD

**Issue by IanEmmons** [RMLio/rmlmapper-java#127]
My application translates a several kinds of data files into RDF using rmlmapper.  Currently, this application forks a separate JVM process to translate each file, using the command-line interface of the "fat" rmlmapper jar.  However, I am mapping hundreds of thousands of files, so I would like to avoid the overhead of starting a new JVM process for each file.  Thus I am trying to use the non-fat rmlmapper jar as an in-process library.  However, before I change a single line of code, if I simply add rmlmapper as a dependency in my Gradle script, I get the following exception in my unit tests:

```
java.lang.NoClassDefFoundError: org/apache/jena/sparql/lib/Metadata
   at org.apache.jena.tdb2.TDB2.<clinit>(TDB2.java:163)
   at org.apache.jena.tdb2.sys.InitTDB2.start(InitTDB2.java:28)
   at org.apache.jena.sys.JenaSystem.lambda$init$2(JenaSystem.java:117)
   at java.util.ArrayList.forEach(ArrayList.java:1259)
   at org.apache.jena.sys.JenaSystem.forEach(JenaSystem.java:192)
   at org.apache.jena.sys.JenaSystem.forEach(JenaSystem.java:169)
   at org.apache.jena.sys.JenaSystem.init(JenaSystem.java:115)
   at com.bbn.ix.sunrise.etl.FileSourceRmlTest.<clinit>(FileSourceRmlTest.java:12)
   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
   at org.junit.platform.commons.util.ReflectionUtils.newInstance(ReflectionUtils.java:513)
   at org.junit.jupiter.engine.execution.ConstructorInvocation.proceed(ConstructorInvocation.java:56)
```

I've shown the stack trace down to the point where JUnit is calling into my code.  You can see that the static constructor of my test case has called the initialization code for Jena, which immediately fails before my code does anything.  In the original version of my code, I did not explicitly call Jena's initialization, but rather simply created a default Model in my test case, causing Jena to call its own initialization code.  I added the explicit initialization to eliminate several lines from the stack trace, but the top seven lines are the same either way.  I have not been able to find the exact cause of this error, but it seems like an issue resolving all the dependencies in a way that does not cause conflicts.  When I list the dependencies using Gradle, I note the following:

* rmlmapper depends on com.spotify:docker-client, which in turn depends on Jena TDB and Fuseki, and which pull in version 3.9.0 of the underlying Jena libraries.
* rmlmapper depends on com.github.rdfhdt:hdt-java, which in turn depends on Jena version 3.13.1.
* I depend directly on Jena version 3.14.0.  Changing this to 3.8.0, 3.9.0, or 3.13.1 has no effect — the same error happens in each case.

(I can upload the full dependency listing if you like, but it's very very long, and in the end I suspect not that helpful.)

What I would like to see is for rmlmapper to be refactored into a plain Java library designed to be called in-process, together with one or more other jars that implement some of the "bells and whistles" that are currently bundled in.  In other words, the refactored library would not contain any of the following:

* A command-line interface
* Docker functionality
* Fuseki — in fact probably not Jena in any form, since the mapper itself appears to be using RDF4J

Further, this library should not depend on any other software that is not necessary to executing an RML script over an input file to produce RDF.

**Comment by IanEmmons** [comment]
Super, thanks!
