### ISSUE TITLE
is it possible to map TSV? 

### ISSUE THREAD

**Issue by m1ci** [RMLio/rmlmapper-java#22]
Hi there,
I have a TSV that I would like to map to RDF. 
Is it possible to configure mapping of TSV to RDF? If yes, how?

there is
`rml:referenceFormulation ql:CSV `
but is there smth like `rml:referenceFormulation ql:TSV ` ?

Thanks,
Milan

**Comment by pheyvaer** [comment]
Hi @m1ci,

At the moment this is not supported, but we will do this in the future, once we have support CSVW, which has support for a custom delimiter. See also #20.

**Comment by m1ci** [comment]
OK, thanks for the quick response, Pieter! btw, nice to hear from you, long time no see! ;) take care!

**Comment by bjdmeest** [comment]
Hi, our new [v4.4.0 release](https://github.com/RMLio/rmlmapper-java/releases/tag/v4.4.0) supports CSVW dialects, of which tab-delimiters should be possible, see for example https://github.com/RMLio/rmlmapper-java/tree/master/src/test/resources/test-cases-CSVW/RMLTC0002a_delimiter-CSVW

**Comment by mathib** [comment]
@bjdmeest : I just tried the mapping file using CSVW in RML-mapper v4.5.1 and I found that it errors if the URI of the `csvw:Table` instance is `<#CSVW_source>`:
```
org.eclipse.rdf4j.rio.RDFParseException: Not a valid (absolute) IRI: #CSVW_source [line 18]
        at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportFatalError(RDFParserHelper.java:366)
        at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.reportFatalError(AbstractRDFParser.java:761)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.reportFatalError(TurtleParser.java:1313)
        at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.createURI(AbstractRDFParser.java:418)
        at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.resolveURI(AbstractRDFParser.java:401)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseURI(TurtleParser.java:943)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseValue(TurtleParser.java:575)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseObject(TurtleParser.java:461)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseObjectList(TurtleParser.java:389)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parsePredicateObjectList(TurtleParser.java:362)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseImplicitBlank(TurtleParser.java:552)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseObject(TurtleParser.java:458)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseObjectList(TurtleParser.java:389)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parsePredicateObjectList(TurtleParser.java:362)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseTriples(TurtleParser.java:349)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseStatement(TurtleParser.java:216)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:178)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:130)
        at org.eclipse.rdf4j.rio.Rio.parse(Rio.java:253)
        at be.ugent.rml.Utils.readTurtle(Utils.java:244)
        at be.ugent.rml.cli.Main.main(Main.java:136)
        at be.ugent.rml.cli.Main.main(Main.java:30)
Caused by: java.lang.IllegalArgumentException: Not a valid (absolute) IRI: #CSVW_source
        at org.eclipse.rdf4j.model.impl.SimpleIRI.setIRIString(SimpleIRI.java:74)
        at org.eclipse.rdf4j.model.impl.SimpleIRI.<init>(SimpleIRI.java:63)
        at org.eclipse.rdf4j.model.impl.AbstractValueFactory.createIRI(AbstractValueFactory.java:86)
        at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.createURI(AbstractRDFParser.java:416)
        ... 18 more
```
It works however if it's replaced with `<http://example.org#CSVW_source1>`

**Comment by bjdmeest** [comment]
Huh, could it be that there's no @base in you mapping file? The error suggests indeed that you need an absolute URI, which you won't have without @base. If you do have one, this feels like it should belong in a new issue :)

**Comment by mathib** [comment]
That's correct! My bad :/

It works with a @base
