### ISSUE TITLE
Support SQLite db

### ISSUE THREAD

**Issue by brechtvdv** [RMLio/rmlmapper-java#52]
I need to map a geopackage file, which is a SQLite database, for the smart waterway project (ends in 2021)

For now, I will try converting the SQLite to MySQL and start from there.

**Comment by pheyvaer** [comment]
Hi @brechtvdv 

I haven't tried the following, but it _should_ work:

1. Download the JDBC driver for SQLite. If found some [here](https://bitbucket.org/xerial/sqlite-jdbc/downloads/).
2. Run the RMLMapper with the extra jar of the JDBC driver via `java -cp 'rmlmapper.jar:your-jdbc-driver.jar' be.ugent.rml.cli.Main -m rules.rml.ttl`
3. Use the JDBC driver in the RML rules. This will be something like `jdbc:sqlite:sqlite_database_file_path`, based on this [tutorial](https://www.sqlitetutorial.net/sqlite-java/sqlite-jdbc-driver/).

Let me know if that works!

**Comment by KTBL-DanielMartini** [comment]
Hi @pheyvaer 

I recently had the same requirement as the OP: having to map from a SQLite database. I tried a few things and can give more information. Maybe the issue can then be opened up again, but in fact I found that it's a bit more involved (thus the description a bit lengthy):

Following the steps outlined above and issueing the command as (roughly) pointed out, in detail like so: `java -cp 'C:\Users\d.martini\src\rmlmapper-java\target\rmlmapper-4.15.0-r361-all.jar;sqlite-jdbc-3.36.0.3.jar' be.ugent.rml.cli.Main -m testcase-map-sqlite.ttl -o testcase-sqlite-out.ttl` gave me this exception:

```
Exception in thread "main" java.lang.Error: Couldn't find a driver for the given DB: org.sqlite.JDBC
        at be.ugent.rml.access.DatabaseType.getDBtype(DatabaseType.java:76)
        at be.ugent.rml.access.AccessFactory.getRDBAccess(AccessFactory.java:215)
        at be.ugent.rml.access.AccessFactory.getAccess(AccessFactory.java:66)
        at be.ugent.rml.records.RecordsFactory.createRecords(RecordsFactory.java:54)
        at be.ugent.rml.Executor.getRecords(Executor.java:429)
        at be.ugent.rml.Executor.executeWithFunctionV5(Executor.java:165)
        at be.ugent.rml.Executor.executeV5(Executor.java:152)
        at be.ugent.rml.cli.Main.main(Main.java:370)
        at be.ugent.rml.cli.Main.main(Main.java:44)
```

The mapping file only contained a very simple test case - in total:

```
@prefix d2rq: <http://www.wiwiss.fu-berlin.de/suhl/bizer/D2RQ/0.1#> .
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix rml: <http://semweb.mmlab.be/ns/rml#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ex: <http://example.com/ns#> .
@base <http://example.com/base> .

<#DB_source> a d2rq:Database;
    d2rq:jdbcDSN "jdbc:sqlite:c:/Users/d.martini/src/rmlmapper-testcases/rmltest.sqlite";
    d2rq:jdbcDriver "org.sqlite.JDBC";
    d2rq:username "";
    d2rq:password "" .

<#TriplesMap1> a rr:TriplesMap ;
    rml:logicalSource [
        rml:source <#DB_source>;
        rr:sqlVersion rr:SQL2008;
        rr:tableName "test" ;
        rr:query "SELECT * from test";
    ];
    rr:subjectMap [
        rr:template "http://data.example.com/rmltest/{id}";
        rr:class ex:whatever;
    ];
    rr:predicateObjectMap [
        rr:predicate rdfs:label;
        rr:objectMap [rml:reference "label"];
    ].
```

The database exists and the following SQL defines its content:

```
CREATE TABLE test (
    id  INTEGER,
    label    TEXT
);

INSERT INTO test VALUES (1, 'label');
```

It should produce the following output:

```
<http://data.example.com/rmltest/1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/ns#whatever>.
<http://data.example.com/rmltest/1> <http://www.w3.org/2000/01/rdf-schema#label> "label".
```

I have tested the mapping against a PostgreSQL database with identical content using a mapping file with an adjusted `d2rq:Database` instance and it was all fine with that - so the mapping as such should work.

Diving into the code that the exception pointed to indicated that SQLite has to be added to the DatabaseType public enum [starting in (currently) line 9 of DatabaseType.java](https://github.com/RMLio/rmlmapper-java/blob/22b2e06f6b4afb8aa614b82313ce1a2844e8850b/src/main/java/be/ugent/rml/access/DatabaseType.java#L9). So I added the following entry:

```
SQLITE3("SQLite3",
            "sqlite:",
            "sqlite",
            "org.sqlite.JDBC")
```

With that modification in place I got the following error message:

```
10:10:41.268 [main] ERROR be.ugent.rml.cli.Main               .main(390) - path to '//dbc:sqlite:c:/Users/d.martini/src/rmlmapper-testcases/rmltest.sqlite': '\\' does not exist
```

which suggests that the jdbcDSN somehow got messed up. I was able to fix it by overriding the generated DSN by adding the following code snippet [to RDBAccess.java after line 81](https://github.com/RMLio/rmlmapper-java/blob/22b2e06f6b4afb8aa614b82313ce1a2844e8850b/src/main/java/be/ugent/rml/access/RDBAccess.java#L81):

```
if (databaseType == DatabaseType.SQLITE3) {
    jdbcDSN = "j" + dsn;
}
```

Voilà, that made the mapping work without any further errors or exceptions. So the `git diff` leading up to this looks like this:

```
diff --git a/src/main/java/be/ugent/rml/access/DatabaseType.java b/src/main/java/be/ugent/rml/access/DatabaseType.java
index 189c274b..88092e89 100644
--- a/src/main/java/be/ugent/rml/access/DatabaseType.java
+++ b/src/main/java/be/ugent/rml/access/DatabaseType.java
@@ -27,7 +27,11 @@ public enum DatabaseType {
     DB2("IBM DB2",
             "as400:",
             "ibm",
-            "com.ibm.as400.access.AS400JDBCDriver");
+            "com.ibm.as400.access.AS400JDBCDriver"),
+    SQLITE3("SQLite3",
+            "sqlite:",
+            "sqlite",
+            "org.sqlite.JDBC");

     private final String name;
     private final String jdbcPrefix;
diff --git a/src/main/java/be/ugent/rml/access/RDBAccess.java b/src/main/java/be/ugent/rml/access/RDBAccess.java
index 4af8d351..c2c653e9 100644
--- a/src/main/java/be/ugent/rml/access/RDBAccess.java
+++ b/src/main/java/be/ugent/rml/access/RDBAccess.java
@@ -79,7 +79,9 @@ public class RDBAccess implements Access {
         String jdbcDriver = databaseType.getDriver();
         String jdbcDSN = "jdbc:" + databaseType.getJDBCPrefix() + "//" + dsn;
         InputStream inputStream = null;
-
+        if (databaseType == DatabaseType.SQLITE3) {
+            jdbcDSN = "j" + dsn;
+        }
         try {
             // Register JDBC driver
             Class.forName(jdbcDriver);
```

I think however, my solution is not the correct way to handle things and more of a quick, ugly hack. An `if` clause on `databaseType` should probably be moved down a few lines into the `try/catch` block and there are still some other issues remaining: For example, if you remove the empty `d2rq:username` and `d2rq:password` properties from the mapping file, you will get this exception:

```
Exception in thread "main" java.lang.Error: The database source object <http://example.com/base#DB_source> does not include a username.
        at be.ugent.rml.access.AccessFactory.getRDBAccess(AccessFactory.java:249)
        at be.ugent.rml.access.AccessFactory.getAccess(AccessFactory.java:66)
        at be.ugent.rml.records.RecordsFactory.createRecords(RecordsFactory.java:54)
        at be.ugent.rml.Executor.getRecords(Executor.java:429)
        at be.ugent.rml.Executor.executeWithFunctionV5(Executor.java:165)
        at be.ugent.rml.Executor.executeV5(Executor.java:152)
        at be.ugent.rml.cli.Main.main(Main.java:370)
        at be.ugent.rml.cli.Main.main(Main.java:44)
```

As SQLite is a file based, embedded database, it has no notion of a database user - so handling this gracefully might require another `if` somewhere else in the code.

I'm not sure whether I'd be capable of producing a high quality production level patch for the issue as Java is not my primary programming language currently and I'm therefore not that familiar with it. But if you want to tackle SQLite support once more, I'd definitely be willing to continue exchange on this thread and test or try things out.

**Comment by DylanVanAssche** [comment]
Hi @KTBL-DanielMartini!

Thanks for looking into this!
Integrating SQLite might need such changes as you proposed, but also the test cases must be expanded to verify if all test cases work as well with SQLite. If you're interested into getting support for this in the RMLMapper, we really appreciate PRs :) 


> which suggests that the jdbcDSN somehow got messed up. I was able to fix it by overriding the generated DSN by adding the following code snippet [to RDBAccess.java after line 81](https://github.com/RMLio/rmlmapper-java/blob/22b2e06f6b4afb8aa614b82313ce1a2844e8850b/src/main/java/be/ugent/rml/access/RDBAccess.java#L81):

Looks good! That's indeed how to add support for other database types.

> An if clause on databaseType should probably be moved down a few lines into the try/catch block and there are still some other issues 

Probably, all the connection specific parts are done there, makes sense.

> I think however, my solution is not the correct way to handle things and more of a quick, ugly hack. An if clause on databaseType should probably be moved down a few lines into the try/catch block and there are still some other issues remaining: For example, if you remove the empty d2rq:username and d2rq:password properties from the mapping file, you will get this exception:

Yeah this might need some additional work... But it is an excellent start!
