### ISSUE TITLE
Generating metadata in different RDF format

### ISSUE THREAD

**Issue by AurisAudentis** [RMLio/rmlmapper-java#68]
When specifying both a metadata file (-e option) and a format option (-s) the application crashes.

The following command **works**:
`java -jar rmlmapper-4.8.0-r247.jar -m mapping.rml.ttl -s turtle`

The following command **does not work**:
`java -jar rmlmapper-4.8.0-r247.jar -m mapping.rml.ttl -s turtle -l triple -e metadata.turtle`
and instead outputs: 
```
Exception in thread "main" java.lang.Error: Serialization turtle not supported at be.ugent.rml.store.SimpleQuadStore.write(SimpleQuadStore.java:97)  
at be.ugent.rml.cli.Main.writeOutputUncompressed(Main.java:413)  
at be.ugent.rml.cli.Main.writeOutput(Main.java:379)
at be.ugent.rml.cli.Main.main(Main.java:295)                                                                                                                         
at be.ugent.rml.cli.Main.main(Main.java:35)  
```

I was able to work around this issue by changing the used store of the MetadataGenerator to RDF4JStore here:
https://github.com/RMLio/rmlmapper-java/blob/fb2d8d7ace3eb5bb3d0a1f3913b8d92185726e35/src/main/java/be/ugent/rml/metadata/MetadataGenerator.java#L54

-Mggeldho

**Comment by pheyvaer** [comment]
Thanks! Will have a look at it.
