### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by philbarker** [RMLio/rmlmapper-java#69]
Any further guidance on installation would help. Thanks :)

Using Ubuntu 20.04, Java(TM) SE Runtime Environment (build 1.8.0_181-b13)

on `mvn install` I get lots of output ending with:

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in be.ugent.rml.Mapper_OracleDB_Test
[ERROR] doMapping[0: OracleDB_RMLTC0001a](be.ugent.rml.Mapper_OracleDB_Test)  Time elapsed: 0 s  <<< ERROR!
java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:rmlmapper_test/test@//hp074.utah.cloudlab.us:1521/XE
	at be.ugent.rml.Mapper_OracleDB_Test.mappingTest(Mapper_OracleDB_Test.java:120)
	at be.ugent.rml.Mapper_OracleDB_Test.doMapping(Mapper_OracleDB_Test.java:104)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   Mapper_OracleDB_Test.doMapping:104->mappingTest:120 » SQL No suitable driver f...
[INFO] 
[ERROR] Tests run: 393, Failures: 0, Errors: 1, Skipped: 7
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:39 min
[INFO] Finished at: 2020-08-04T11:38:35+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project rmlmapper: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/phil/Share/Projects/RML/rmlmapper-java/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by pheyvaer** [comment]
Hi @philbarker 

Best is to build without running the tests. The reason why the Oracle tests are failing is because the Oracle driver jar is not published, so you have to include it manually and then run the tests. More info about using the RMLMapper with Oracle can be found [here](https://github.com/RMLio/rmlmapper-java#accessing-oracle-database). To run all tests except the Oracle ones, you can have a look at `test.sh -h`.

Let me know if this helps!

**Comment by philbarker** [comment]
@pheyvaer Thanks! `mvn install -DskipTests` did the trick (at least as far as getting a runnable jar)

**Comment by pheyvaer** [comment]
Great! If there is anything else, just let us know via this issue or a new one :smile:
